import type { CatalogSnapshot } from "@/lib/catalog";

export const fallbackCatalog: CatalogSnapshot = {
  rateBcv: 250,
  settings: {
    announcementEnabled: true,
    announcementText: "Envíos a toda Venezuela · Atención directa por WhatsApp",
    announcementLink: null,
    whatsappPhone: "584225329551",
    locationText: "Portuguesa, Venezuela",
    shippingText: "Envíos a toda Venezuela por MRW, Zoom y Tealca",
    wholesaleTitle: "Precios especiales para equipos, academias y comercios",
    wholesaleText: "Consulta condiciones por cantidad y recibe atención personalizada.",
  },
  banners: [
    {
      id: 1,
      title: "La Casa del Softball",
      subtitle: "Pelotas, equipamiento y artículos deportivos para llevar tu juego al siguiente nivel.",
      imageUrl: "/products/tamanaco-pack3.png",
      mobileImageUrl: "/products/tamanaco-pack3.png",
      ctaText: "Ver productos",
      ctaHref: "#productos",
      active: true,
      sortOrder: 1,
    },
  ],
  paymentMethods: [
    { id: 1, name: "Zelle", detail: "Precio en divisas" },
    { id: 2, name: "USDT", detail: "Precio en divisas" },
    { id: 3, name: "Divisas", detail: "Efectivo en USD" },
    { id: 4, name: "Depósito bancario", detail: "Precio en divisas" },
    { id: 5, name: "Pago móvil", detail: "Monto en Bs. según tasa vigente" },
    { id: 6, name: "Transferencia Bs.", detail: "Monto en Bs. según tasa vigente" },
  ],
  products: [
    {
      id: 1,
      name: "Pelota Softball Tamanaco SB-120I",
      slug: "pelota-softball-tamanaco-sb-120i",
      sku: "TAM-SB120I-1",
      brand: "Tamanaco",
      category: "Pelotas",
      subtitle: "Importada · Bolsa Chillona",
      description: "Pelota de softball Tamanaco SB-120I importada. Diseñada para entrenamiento, juego y competencia, con excelente presencia y terminación.",
      image: "/products/tamanaco-sb120i.png",
      badge: "Más vendida",
      labels: ["TOP", "IMPORTADA", "SOFTBALL"],
      priceUsd: 7,
      bcvReferenceUsd: 9.5,
      stock: 50,
      featured: true,
      rating: 5,
      reviewCount: 2,
      freeShipping: true,
      warrantyDays: 1,
      wholesaleEnabled: true,
      wholesaleNote: "Consulta precios especiales por cantidad para equipos, academias, comercios y revendedores.",
      images: [
        { id: 1, imageUrl: "/products/tamanaco-sb120i.png", altText: "Pelota Tamanaco SB-120I", sortOrder: 0 },
      ],
      wholesaleTiers: [
        { id: 1, minQuantity: 6, priceUsd: 6.5, bcvReferenceUsd: 9, label: "Desde 6 unidades" },
      ],
    },
    {
      id: 2,
      name: "3 Pelotas Softball Tamanaco SB-120I",
      slug: "pack-3-tamanaco-sb-120i",
      sku: "TAM-SB120I-P3",
      brand: "Tamanaco",
      category: "Pelotas",
      subtitle: "Pack de 3 unidades · Bolsa Chillona",
      description: "Pack de 3 pelotas de softball Tamanaco SB-120I importadas, ideal para equipos, entrenamientos y reposición.",
      image: "/products/tamanaco-pack3.png",
      badge: "Pack 3",
      labels: ["PACK", "IMPORTADA", "SOFTBALL"],
      priceUsd: 38,
      bcvReferenceUsd: 42,
      stock: 20,
      featured: false,
      rating: 5,
      reviewCount: 2,
      freeShipping: true,
      warrantyDays: 1,
      wholesaleEnabled: true,
      wholesaleNote: "Disponible con condiciones especiales al mayor.",
      images: [
        { id: 2, imageUrl: "/products/tamanaco-pack3.png", altText: "Pack 3 Tamanaco SB-120I", sortOrder: 0 },
      ],
      wholesaleTiers: [],
    },
  ],
};
